# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders :
      AppBundle\Entity\User:
        algorithm : md5
        encode_as_base64 : false
        iterations : 0
    providers:
        #in_memory:
        #    memory: ~
        my_entity_provider:
          entity :
            class : AppBundle:User
            property : name
            manager_name : ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            provider : my_entity_provider
            form_login:
                login_path : login
                check_path : login
                username_parameter : username
                password_parameter : password
                post_only : true
                always_use_default_target_path : true
                default_target_path : user_list
                failure_path : /
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            logout:
              path : /logout
              target : /
              invalidate_session : false
    access_control:
      - { path : ^/user, roles : ROLE_ADMIN}